import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col bg-slate-300">
          <div className="flex-shrink-0 bg-red-300">
            <Header />
          </div>
          <div className="flex-grow bg-cyan-500">{children}</div>
          <div className="flex-shrink-0 bg-fuchsia-300">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
